#!/bin/bash

fullscreen=false
while :; do
	#Try getting active window again if it fails
	active_window=$(xdotool getactivewindow 2> /dev/null) || continue

	#Monitor active window
	while read line; do
		[[ "$line" != *"FOCUSED"* ]] && break #Window lost focus

		if [[ "$line" == *"FULLSCREEN"* ]]; then
			if ! $fullscreen; then
				echo "Screensaver disabled"

				#Window state changed to fullscreen
				fullscreen=true
				xset s off
				xset -dpms
			fi
		elif $fullscreen; then
			echo "Screensaver enabled"

			#Window no longer fullscreen
			fullscreen=false
			xset s on
			xset +dpms
		fi
	done < <(exec xprop -id $active_window -spy _NET_WM_STATE)
done
