#!/bin/bash
focused=true
fullscreen=false
while :; do
	active_window=$(xdotool getactivewindow)

	#Monitor active window
	fullscreen=$(xprop -id $active_window -spy _NET_WM_STATE |
		while read line; do
			if [[ "$line" != *"FOCUSED"* ]]; then
				echo "$fullscreen" #Window lost focus
				kill $!
			elif [[ "$line" == *"FULLSCREEN"* ]]; then
				if ! $fullscreen; then
					>&2 echo "Screensaver disabled"

					#Window state changed to fullscreen
					fullscreen=true
					xset s off
					xset -dpms
				fi
			elif $fullscreen; then
				>&2 echo "Screensaver enabled"

				#Window no longer fullscreen
				fullscreen=false
				xset s on
				xset +dpms
			fi
		done &)
done
