#!/bin/bash

xprop -spy -root _NET_ACTIVE_WINDOW |
	while read line; do
		kill $! 2> /dev/null

		fullscreen=false
		window_id=${line##*# }
		window_id=${window_id%,*}

		[ "$window_id" = "0x0" ] && continue

		xprop -id $window_id -spy _NET_WM_STATE |
			while read line; do
				if [[ "$line" == *"_NET_WM_STATE_FULLSCREEN"* ]]; then
					echo "$window_id fullscreen"
					fullscreen=true
					xset s off
					xset -dpms
				elif $fullscreen; then
					echo "$window_id windowed"
					fullscreen=false
					xset s on
					xset +dpms
				fi
			done &
	done
